services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage

  rag-api:
      build:
        context: .
      container_name: rag-api
      depends_on:
        - qdrant
      ports:
        - "8000:8000"
      env_file:
        - .env
      environment:
        QDRANT_URL: "http://qdrant:6333"
      restart: unless-stopped

configs:
  qdrant_config:
    content: |
      log_level: INFO